name: Deploy to EKS

on:
  # Allows manual triggers via the GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
      version:
        description: 'App version to deploy'
        required: false
  # Trigger on push to main and pull requests
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the source code
      - name: Check out the repository
        uses: actions/checkout@v3
        
      # 2. Set up Node 18 (if needed for npm tasks)
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install dependencies, then build the project if you need it outside Docker
      #    (Otherwise, Docker will handle the build inside the container)
      - name: Install dependencies
        run: |
          npm install --save-dev typescript@^4.9.5
          cd frontend
          npm install --legacy-peer-deps

      # 4. Configure AWS credentials (pull from GitHub Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if your cluster/ECR is in a different region

      # 5. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      # 6. Update kubeconfig to point to your EKS cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name jmlab-eks-cluster

      # 7. Build Docker image (references your Dockerfile with build tools installed)
      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      # 8. Log in to Amazon ECR
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin jm-lab

      # 9. Tag and push Docker image to ECR
      - name: Tag and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag juice-shop:latest jm-lab/juiceshop:$IMAGE_TAG
          docker push jm-lab/juiceshop:$IMAGE_TAG

      # 10. Deploy to EKS by updating the existing Kubernetes Deployment
      - name: Deploy to EKS
        run: |
          IMAGE_TAG=${{ github.sha }}
          kubectl set image deployment/juice-shop \
            juice-shop=jm-lab/juiceshop:$IMAGE_TAG
