name: Deploy to EKS

on:
  # Allows manual triggers via the GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "production"
      version:
        description: "App version to deploy"
        required: false
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Set up Node.js 18 (if needed for npm tasks)
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install dependencies and build frontend dependencies
      - name: Install dependencies
        run: |
          npm install --save-dev typescript@^4.9.5
          cd frontend
          npm install --legacy-peer-deps

      # 4. Configure AWS credentials using static keys from GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      # 6. Reset old kubeconfig if it exists
      - name: Reset kubeconfig
        run: rm -f $HOME/.kube/config

      # 7. Update kubeconfig to point to your EKS cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name jmlab-eks-cluster

      # 8. Set the current kubeconfig context to use the user "github-eks-deploy"
      - name: Set kubeconfig context user
        run: |
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Setting current context ($CURRENT_CONTEXT) user to github-eks-deploy"
          kubectl config set-context "$CURRENT_CONTEXT" --user=github-eks-deploy

      # 9. Build Docker image (using your Dockerfile)
      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      # 10. Log in to Amazon ECR (replace with your account's registry)
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin 285653935315.dkr.ecr.us-east-1.amazonaws.com

      # 11. Tag and push Docker image to ECR
      - name: Tag and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag juice-shop:latest 285653935315.dkr.ecr.us-east-1.amazonaws.com/jm-lab/juiceshop:$IMAGE_TAG
          docker push 285653935315.dkr.ecr.us-east-1.amazonaws.com/jm-lab/juiceshop:$IMAGE_TAG

      # 12. Deploy to EKS by updating the Kubernetes Deployment
      - name: Deploy to EKS
        run: |
          IMAGE_TAG=${{ github.sha }}
          kubectl set image deployment/juice-shop -n jm-lab \
            juice-shop=285653935315.dkr.ecr.us-east-1.amazonaws.com/jm-lab/juiceshop:$IMAGE_TAG
