name: Deploy to EKS

on:
  # Allows manual triggers via the GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
      version:
        description: 'App version to deploy'
        required: false
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the source code
      - name: Check out the repository
        uses: actions/checkout@v3
        
      # 2. Set up Node.js 18 (if needed for npm tasks)
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install dependencies and build the project (adjust as needed)
      - name: Install dependencies
        run: |
          npm install --save-dev typescript@^4.9.5
          cd frontend
          npm install --legacy-peer-deps

      # 4. Configure AWS credentials using static keys from GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5. Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

     # 4. Update kubeconfig to point to your EKS cluster
      - name: Update kubeconfig
        run: |
          rm -f $HOME/.kube/config
          aws eks update-kubeconfig --region us-east-1 --name jmlab-eks-cluster

      # 5a. Update the current kubeconfig context to use the user "github-eks-deploy"
      - name: Set kubeconfig context user
        run: |
          CURRENT_CONTEXT=$(kubectl config current-context)
          echo "Setting current context ($CURRENT_CONTEXT) user to github-eks-deploy"
          kubectl config set-context "$CURRENT_CONTEXT" --user=github-eks-deploy

      # 6a. Rename kubeconfig user to your IAM user "github-eks-deploy"
      - name: Rename kubeconfig user
        run: |
          CURRENT_USER=$(kubectl config view -o jsonpath='{.users[0].name}')
          echo "Renaming kubeconfig user from $CURRENT_USER to github-eks-deploy"
          kubectl config rename-user "$CURRENT_USER" github-eks-deploy

      # 7. Build Docker image (using your Dockerfile)
      - name: Build Docker image
        run: docker build -t juice-shop:latest .

      # 8. Log in to Amazon ECR using the fully qualified registry endpoint
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin 285653935315.dkr.ecr.us-east-1.amazonaws.com

      # 9. Tag and push Docker image to ECR
      - name: Tag and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag juice-shop:latest 285653935315.dkr.ecr.us-east-1.amazonaws.com/juiceshop:$IMAGE_TAG
          docker push 285653935315.dkr.ecr.us-east-1.amazonaws.com/juiceshop:$IMAGE_TAG

      # 10. Deploy to EKS by updating the existing Kubernetes Deployment
      - name: Deploy to EKS
        run: |
          IMAGE_TAG=${{ github.sha }}
          kubectl set image deployment/juice-shop -n jm-lab \
            juice-shop=285653935315.dkr.ecr.us-east-1.amazonaws.com/juiceshop:$IMAGE_TAG
